/**
 * Export Service
 * Handles exporting predictions to various formats (HTML, PDF-ready, JSON)
 */

/**
 * Export predictions to HTML format
 */
function exportToHTML(predictions, examInfo, stats) {
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', month: 'long', day: 'numeric' 
  });
  
  const questionsHTML = predictions.map((q, i) => `
    <div class="question">
      <div class="question-header">
        <span class="question-number">Q${i + 1}.</span>
        <span class="badge ${q.difficulty.toLowerCase()}">${q.difficulty}</span>
        <span class="badge probability">${Math.round(q.probability * 100)}% likely</span>
      </div>
      <p class="question-text">${escapeHtml(q.question)}</p>
      <div class="question-meta">
        <span><strong>Topic:</strong> ${escapeHtml(q.topic)}</span>
        <span><strong>Type:</strong> ${q.type}</span>
        <span><strong>Section:</strong> ${q.section || 'A'}</span>
      </div>
      ${q.rationale ? `<p class="rationale"><em>Why: ${escapeHtml(q.rationale)}</em></p>` : ''}
    </div>
  `).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Predicted Question Paper - ${escapeHtml(examInfo.subject)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #4f46e5; }
    .header h1 { color: #4f46e5; margin-bottom: 10px; }
    .header .meta { color: #666; font-size: 14px; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 30px; }
    .stat { background: #f5f5f5; padding: 15px; border-radius: 8px; text-align: center; }
    .stat-value { font-size: 24px; font-weight: bold; color: #4f46e5; }
    .stat-label { font-size: 12px; color: #666; }
    .question { background: #fff; border: 1px solid #e5e5e5; border-radius: 8px; padding: 20px; margin-bottom: 15px; }
    .question-header { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; }
    .question-number { font-weight: bold; font-size: 18px; color: #4f46e5; }
    .badge { padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: 500; }
    .easy { background: #d1fae5; color: #065f46; }
    .medium { background: #fef3c7; color: #92400e; }
    .hard { background: #fee2e2; color: #991b1b; }
    .probability { background: #e0e7ff; color: #3730a3; }
    .question-text { font-size: 16px; margin-bottom: 10px; }
    .question-meta { display: flex; gap: 20px; font-size: 13px; color: #666; margin-bottom: 10px; }
    .rationale { font-size: 13px; color: #666; background: #f9fafb; padding: 10px; border-radius: 4px; }
    .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e5e5; color: #666; font-size: 12px; }
    @media print { body { padding: 0; } .question { break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Predicted Question Paper</h1>
    <div class="meta">
      <p><strong>${escapeHtml(examInfo.name)}</strong> - ${escapeHtml(examInfo.subject)} (${escapeHtml(examInfo.subjectCode)})</p>
      <p>Generated on ${date} by PredictWiseAI</p>
    </div>
  </div>
  
  <div class="stats">
    <div class="stat"><div class="stat-value">${stats.papersAnalyzed}</div><div class="stat-label">Papers Analyzed</div></div>
    <div class="stat"><div class="stat-value">${stats.questionsExtracted}</div><div class="stat-label">Questions Found</div></div>
    <div class="stat"><div class="stat-value">${stats.topicsCovered}</div><div class="stat-label">Topics Covered</div></div>
    <div class="stat"><div class="stat-value">${stats.avgAccuracy}%</div><div class="stat-label">Confidence</div></div>
  </div>
  
  <div class="questions">
    ${questionsHTML}
  </div>
  
  <div class="footer">
    <p>Generated by PredictWiseAI - AI-Powered Exam Prediction</p>
    <p>Note: These predictions are based on historical patterns and should be used as study guidance only.</p>
  </div>
</body>
</html>`;
}

/**
 * Export predictions to JSON format
 */
function exportToJSON(predictions, examInfo, stats) {
  return JSON.stringify({
    exportDate: new Date().toISOString(),
    exam: examInfo,
    statistics: stats,
    predictions: predictions.map((p, i) => ({
      number: i + 1,
      ...p,
      probabilityPercent: Math.round(p.probability * 100)
    })),
    metadata: {
      generator: 'PredictWiseAI',
      version: '1.0.0'
    }
  }, null, 2);
}

/**
 * Export predictions to plain text format
 */
function exportToText(predictions, examInfo, stats) {
  const lines = [
    '=' .repeat(60),
    'PREDICTED QUESTION PAPER',
    '=' .repeat(60),
    '',
    `Exam: ${examInfo.name}`,
    `Subject: ${examInfo.subject} (${examInfo.subjectCode})`,
    `Generated: ${new Date().toLocaleDateString()}`,
    '',
    '-'.repeat(60),
    `Papers Analyzed: ${stats.papersAnalyzed}`,
    `Questions Extracted: ${stats.questionsExtracted}`,
    `Topics Covered: ${stats.topicsCovered}`,
    `Confidence: ${stats.avgAccuracy}%`,
    '-'.repeat(60),
    '',
    'PREDICTED QUESTIONS',
    '=' .repeat(60),
    ''
  ];

  predictions.forEach((q, i) => {
    lines.push(`Q${i + 1}. [${q.difficulty}] [${Math.round(q.probability * 100)}% likely]`);
    lines.push(q.question);
    lines.push(`   Topic: ${q.topic}`);
    lines.push(`   Type: ${q.type}`);
    if (q.rationale) {
      lines.push(`   Why: ${q.rationale}`);
    }
    lines.push('');
  });

  lines.push('-'.repeat(60));
  lines.push('Generated by PredictWiseAI');
  lines.push('Note: Use as study guidance only.');

  return lines.join('\n');
}

/**
 * Export predictions to CSV format
 */
function exportToCSV(predictions, examInfo) {
  const headers = ['Number', 'Topic', 'Question', 'Difficulty', 'Type', 'Probability', 'Section', 'Rationale'];
  const rows = predictions.map((p, i) => [
    i + 1,
    `"${escapeCsv(p.topic)}"`,
    `"${escapeCsv(p.question)}"`,
    p.difficulty,
    p.type,
    Math.round(p.probability * 100) + '%',
    p.section || 'A',
    `"${escapeCsv(p.rationale || '')}"`
  ]);

  return [
    `# Predicted Questions for ${examInfo.subject} (${examInfo.subjectCode})`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    headers.join(','),
    ...rows.map(r => r.join(','))
  ].join('\n');
}

// Helper functions
function escapeHtml(text) {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function escapeCsv(text) {
  if (!text) return '';
  return text.replace(/"/g, '""');
}

module.exports = {
  exportToHTML,
  exportToJSON,
  exportToText,
  exportToCSV
};
